/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import sistema.bean.Funcionario;
import sistema.dao.FuncionarioDAO;
import sistema.bean.Ponto;
import sistema.dao.PontoDAO;

/**
 *
 * @author ambiental.pelotas
 */
public class FormRelatorios extends javax.swing.JInternalFrame {

    private JFrame mdi;
    
    /**
     * Creates new form FormRelatorios
     */
    public FormRelatorios(JFrame mdi) {
        this.mdi = mdi;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Opcoes = new javax.swing.JPanel();
        btRelGeral = new javax.swing.JRadioButton();
        btRelIntrajornadas = new javax.swing.JRadioButton();
        btRelIntervalos = new javax.swing.JRadioButton();
        btRelHorasExtras = new javax.swing.JRadioButton();
        btRelFaltas = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("####-##-##"); 
            jTextField1 = new javax.swing.JFormattedTextField(data); 
        } 
        catch (Exception e){ 
        }
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("####-##-##"); 
            jTextField2 = new javax.swing.JFormattedTextField(data); 
        } 
        catch (Exception e){ 
        }
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Geração de Relatórios");

        Opcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        buttonGroup1.add(btRelGeral);
        btRelGeral.setText("Relatório Geral de Inconsistências");
        btRelGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelGeralActionPerformed(evt);
            }
        });

        buttonGroup1.add(btRelIntrajornadas);
        btRelIntrajornadas.setText("Relatório de Infração Intrajornada");
        btRelIntrajornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelIntrajornadasActionPerformed(evt);
            }
        });

        buttonGroup1.add(btRelIntervalos);
        btRelIntervalos.setText("Relatório de Infração de intervalo");
        btRelIntervalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelIntervalosActionPerformed(evt);
            }
        });

        buttonGroup1.add(btRelHorasExtras);
        btRelHorasExtras.setText("Relatório de Horas Extras");
        btRelHorasExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelHorasExtrasActionPerformed(evt);
            }
        });

        buttonGroup1.add(btRelFaltas);
        btRelFaltas.setText("Relatório de Faltas");
        btRelFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelFaltasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpcoesLayout = new javax.swing.GroupLayout(Opcoes);
        Opcoes.setLayout(OpcoesLayout);
        OpcoesLayout.setHorizontalGroup(
            OpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRelFaltas)
                    .addComponent(btRelHorasExtras)
                    .addComponent(btRelIntervalos)
                    .addComponent(btRelIntrajornadas)
                    .addComponent(btRelGeral))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OpcoesLayout.setVerticalGroup(
            OpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btRelFaltas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRelHorasExtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRelIntervalos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRelIntrajornadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRelGeral)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Data inicial:");

        jLabel2.setText("Data final:");

        jButton1.setText("Gerar Relatório");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRelFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelFaltasActionPerformed
        // TODO add your handling code here:
        int opc = 1;
        
    }//GEN-LAST:event_btRelFaltasActionPerformed

    private void btRelHorasExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelHorasExtrasActionPerformed
        // TODO add your handling code here:
        int opc = 2;         
        Funcionario f1 = new Funcionario();
        FuncionarioDAO funcI = new FuncionarioDAO(TelaPrincipal.getConexao());
        
        Ponto p1 = new Ponto();
        PontoDAO pontoI = new PontoDAO(TelaPrincipal.getConexao());
        
        try {            
            pontoI.TesterelatorioHorasExtras(p1);
        } catch (SQLException ex) {
            Logger.getLogger(FormRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRelHorasExtrasActionPerformed

    private void btRelIntervalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelIntervalosActionPerformed
        // TODO add your handling code here:
        int opc = 3;
        Funcionario f1 = new Funcionario();
        FuncionarioDAO funcI = new FuncionarioDAO(TelaPrincipal.getConexao());
        
        Ponto p1 = new Ponto();
        PontoDAO pontoI = new PontoDAO(TelaPrincipal.getConexao());
        
        try {
            pontoI.TesterelatorioIntervalos(p1);
            //pontoI.TestandoRelatorios(p1);
        } catch (SQLException ex) {
            Logger.getLogger(FormRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btRelIntervalosActionPerformed

    private void btRelIntrajornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelIntrajornadasActionPerformed
        // TODO add your handling code here:
        int opc = 4;
    }//GEN-LAST:event_btRelIntrajornadasActionPerformed

    private void btRelGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelGeralActionPerformed
        // TODO add your handling code here:
        int opc = 5;
    }//GEN-LAST:event_btRelGeralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Opcoes;
    private javax.swing.JRadioButton btRelFaltas;
    private javax.swing.JRadioButton btRelGeral;
    private javax.swing.JRadioButton btRelHorasExtras;
    private javax.swing.JRadioButton btRelIntervalos;
    private javax.swing.JRadioButton btRelIntrajornadas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
